// This file is part of ElasticTabstops.
// 
// Copyright (C)2017 Justin Dailey <dail8859@yahoo.com>
// 
// ElasticTabstops is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either
// version 2 of the License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

#pragma once

#include "Scintilla.h"

class ScintillaGateway final {
private:
	HWND scintilla = nullptr;
	SciFnDirect directFunction = nullptr;
	sptr_t directPointer = 0;

public:
	ScintillaGateway() {}

	explicit ScintillaGateway(HWND scintilla) {
		SetScintillaInstance(scintilla);
	}

	void SetScintillaInstance(HWND scintilla) {
		this->scintilla = scintilla;
		directFunction = (SciFnDirect)SendMessage(scintilla, SCI_GETDIRECTFUNCTION, 0, 0);
		directPointer = SendMessage(scintilla, SCI_GETDIRECTPOINTER, 0, 0);
	}

	HWND GetScintillaInstance() const {
		return scintilla;
	}

	template<typename T, typename U>
	inline int Call(unsigned int message, T wParam = 0, U lParam = 0) const {
		sptr_t retVal = directFunction(directPointer, message, (uptr_t)wParam, (sptr_t)lParam);
		return (int)retVal;
	}

	/* ++Autogenerated -- start of section automatically generated from Scintilla.iface */

	void AddText(int length, const char* text) const {
		Call(SCI_ADDTEXT, length, text);
	}

	void AddStyledText(int length, const char* c) const {
		Call(SCI_ADDSTYLEDTEXT, length, c);
	}

	void InsertText(int pos, const char* text) const {
		Call(SCI_INSERTTEXT, pos, text);
	}

	void ChangeInsertion(int length, const char* text) const {
		Call(SCI_CHANGEINSERTION, length, text);
	}

	void ClearAll() const {
		Call(SCI_CLEARALL, SCI_UNUSED, SCI_UNUSED);
	}

	void DeleteRange(int pos, int deleteLength) const {
		Call(SCI_DELETERANGE, pos, deleteLength);
	}

	void ClearDocumentStyle() const {
		Call(SCI_CLEARDOCUMENTSTYLE, SCI_UNUSED, SCI_UNUSED);
	}

	int GetLength() const {
		int res = Call(SCI_GETLENGTH, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	int GetCharAt(int pos) const {
		int res = Call(SCI_GETCHARAT, pos, SCI_UNUSED);
		return res;
	}

	int GetCurrentPos() const {
		int res = Call(SCI_GETCURRENTPOS, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	int GetAnchor() const {
		int res = Call(SCI_GETANCHOR, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	int GetStyleAt(int pos) const {
		int res = Call(SCI_GETSTYLEAT, pos, SCI_UNUSED);
		return res;
	}

	void Redo() const {
		Call(SCI_REDO, SCI_UNUSED, SCI_UNUSED);
	}

	void SetUndoCollection(bool collectUndo) const {
		Call(SCI_SETUNDOCOLLECTION, collectUndo, SCI_UNUSED);
	}

	void SelectAll() const {
		Call(SCI_SELECTALL, SCI_UNUSED, SCI_UNUSED);
	}

	void SetSavePoint() const {
		Call(SCI_SETSAVEPOINT, SCI_UNUSED, SCI_UNUSED);
	}

	int GetStyledText(Sci_TextRange* tr) const {
		int res = Call(SCI_GETSTYLEDTEXT, SCI_UNUSED, tr);
		return res;
	}

	bool CanRedo() const {
		int res = Call(SCI_CANREDO, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	int MarkerLineFromHandle(int handle) const {
		int res = Call(SCI_MARKERLINEFROMHANDLE, handle, SCI_UNUSED);
		return res;
	}

	void MarkerDeleteHandle(int handle) const {
		Call(SCI_MARKERDELETEHANDLE, handle, SCI_UNUSED);
	}

	bool GetUndoCollection() const {
		int res = Call(SCI_GETUNDOCOLLECTION, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	int GetViewWS() const {
		int res = Call(SCI_GETVIEWWS, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetViewWS(int viewWS) const {
		Call(SCI_SETVIEWWS, viewWS, SCI_UNUSED);
	}

	int PositionFromPoint(int x, int y) const {
		int res = Call(SCI_POSITIONFROMPOINT, x, y);
		return res;
	}

	int PositionFromPointClose(int x, int y) const {
		int res = Call(SCI_POSITIONFROMPOINTCLOSE, x, y);
		return res;
	}

	void GotoLine(int line) const {
		Call(SCI_GOTOLINE, line, SCI_UNUSED);
	}

	void GotoPos(int pos) const {
		Call(SCI_GOTOPOS, pos, SCI_UNUSED);
	}

	void SetAnchor(int posAnchor) const {
		Call(SCI_SETANCHOR, posAnchor, SCI_UNUSED);
	}

	int GetCurLine(int length, char* text) const {
		int res = Call(SCI_GETCURLINE, length, text);
		return res;
	}

	int GetEndStyled() const {
		int res = Call(SCI_GETENDSTYLED, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void ConvertEOLs(int eolMode) const {
		Call(SCI_CONVERTEOLS, eolMode, SCI_UNUSED);
	}

	int GetEOLMode() const {
		int res = Call(SCI_GETEOLMODE, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetEOLMode(int eolMode) const {
		Call(SCI_SETEOLMODE, eolMode, SCI_UNUSED);
	}

	void StartStyling(int pos, int mask) const {
		Call(SCI_STARTSTYLING, pos, mask);
	}

	void SetStyling(int length, int style) const {
		Call(SCI_SETSTYLING, length, style);
	}

	bool GetBufferedDraw() const {
		int res = Call(SCI_GETBUFFEREDDRAW, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	void SetBufferedDraw(bool buffered) const {
		Call(SCI_SETBUFFEREDDRAW, buffered, SCI_UNUSED);
	}

	void SetTabWidth(int tabWidth) const {
		Call(SCI_SETTABWIDTH, tabWidth, SCI_UNUSED);
	}

	int GetTabWidth() const {
		int res = Call(SCI_GETTABWIDTH, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void ClearTabStops(int line) const {
		Call(SCI_CLEARTABSTOPS, line, SCI_UNUSED);
	}

	void AddTabStop(int line, int x) const {
		Call(SCI_ADDTABSTOP, line, x);
	}

	int GetNextTabStop(int line, int x) const {
		int res = Call(SCI_GETNEXTTABSTOP, line, x);
		return res;
	}

	void SetCodePage(int codePage) const {
		Call(SCI_SETCODEPAGE, codePage, SCI_UNUSED);
	}

	int GetIMEInteraction() const {
		int res = Call(SCI_GETIMEINTERACTION, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetIMEInteraction(int imeInteraction) const {
		Call(SCI_SETIMEINTERACTION, imeInteraction, SCI_UNUSED);
	}

	void MarkerDefine(int markerNumber, int markerSymbol) const {
		Call(SCI_MARKERDEFINE, markerNumber, markerSymbol);
	}

	void MarkerSetFore(int markerNumber, int fore) const {
		Call(SCI_MARKERSETFORE, markerNumber, fore);
	}

	void MarkerSetBack(int markerNumber, int back) const {
		Call(SCI_MARKERSETBACK, markerNumber, back);
	}

	void MarkerSetBackSelected(int markerNumber, int back) const {
		Call(SCI_MARKERSETBACKSELECTED, markerNumber, back);
	}

	void MarkerEnableHighlight(bool enabled) const {
		Call(SCI_MARKERENABLEHIGHLIGHT, enabled, SCI_UNUSED);
	}

	int MarkerAdd(int line, int markerNumber) const {
		int res = Call(SCI_MARKERADD, line, markerNumber);
		return res;
	}

	void MarkerDelete(int line, int markerNumber) const {
		Call(SCI_MARKERDELETE, line, markerNumber);
	}

	void MarkerDeleteAll(int markerNumber) const {
		Call(SCI_MARKERDELETEALL, markerNumber, SCI_UNUSED);
	}

	int MarkerGet(int line) const {
		int res = Call(SCI_MARKERGET, line, SCI_UNUSED);
		return res;
	}

	int MarkerNext(int lineStart, int markerMask) const {
		int res = Call(SCI_MARKERNEXT, lineStart, markerMask);
		return res;
	}

	int MarkerPrevious(int lineStart, int markerMask) const {
		int res = Call(SCI_MARKERPREVIOUS, lineStart, markerMask);
		return res;
	}

	void MarkerDefinePixmap(int markerNumber, const char* pixmap) const {
		Call(SCI_MARKERDEFINEPIXMAP, markerNumber, pixmap);
	}

	void MarkerAddSet(int line, int set) const {
		Call(SCI_MARKERADDSET, line, set);
	}

	void MarkerSetAlpha(int markerNumber, int alpha) const {
		Call(SCI_MARKERSETALPHA, markerNumber, alpha);
	}

	void SetMarginTypeN(int margin, int marginType) const {
		Call(SCI_SETMARGINTYPEN, margin, marginType);
	}

	int GetMarginTypeN(int margin) const {
		int res = Call(SCI_GETMARGINTYPEN, margin, SCI_UNUSED);
		return res;
	}

	void SetMarginWidthN(int margin, int pixelWidth) const {
		Call(SCI_SETMARGINWIDTHN, margin, pixelWidth);
	}

	int GetMarginWidthN(int margin) const {
		int res = Call(SCI_GETMARGINWIDTHN, margin, SCI_UNUSED);
		return res;
	}

	void SetMarginMaskN(int margin, int mask) const {
		Call(SCI_SETMARGINMASKN, margin, mask);
	}

	int GetMarginMaskN(int margin) const {
		int res = Call(SCI_GETMARGINMASKN, margin, SCI_UNUSED);
		return res;
	}

	void SetMarginSensitiveN(int margin, bool sensitive) const {
		Call(SCI_SETMARGINSENSITIVEN, margin, sensitive);
	}

	bool GetMarginSensitiveN(int margin) const {
		int res = Call(SCI_GETMARGINSENSITIVEN, margin, SCI_UNUSED);
		return res != 0;
	}

	void SetMarginCursorN(int margin, int cursor) const {
		Call(SCI_SETMARGINCURSORN, margin, cursor);
	}

	int GetMarginCursorN(int margin) const {
		int res = Call(SCI_GETMARGINCURSORN, margin, SCI_UNUSED);
		return res;
	}

	void StyleClearAll() const {
		Call(SCI_STYLECLEARALL, SCI_UNUSED, SCI_UNUSED);
	}

	void StyleSetFore(int style, int fore) const {
		Call(SCI_STYLESETFORE, style, fore);
	}

	void StyleSetBack(int style, int back) const {
		Call(SCI_STYLESETBACK, style, back);
	}

	void StyleSetBold(int style, bool bold) const {
		Call(SCI_STYLESETBOLD, style, bold);
	}

	void StyleSetItalic(int style, bool italic) const {
		Call(SCI_STYLESETITALIC, style, italic);
	}

	void StyleSetSize(int style, int sizePoints) const {
		Call(SCI_STYLESETSIZE, style, sizePoints);
	}

	void StyleSetFont(int style, const char* fontName) const {
		Call(SCI_STYLESETFONT, style, fontName);
	}

	void StyleSetEOLFilled(int style, bool filled) const {
		Call(SCI_STYLESETEOLFILLED, style, filled);
	}

	void StyleResetDefault() const {
		Call(SCI_STYLERESETDEFAULT, SCI_UNUSED, SCI_UNUSED);
	}

	void StyleSetUnderline(int style, bool underline) const {
		Call(SCI_STYLESETUNDERLINE, style, underline);
	}

	int StyleGetFore(int style) const {
		int res = Call(SCI_STYLEGETFORE, style, SCI_UNUSED);
		return res;
	}

	int StyleGetBack(int style) const {
		int res = Call(SCI_STYLEGETBACK, style, SCI_UNUSED);
		return res;
	}

	bool StyleGetBold(int style) const {
		int res = Call(SCI_STYLEGETBOLD, style, SCI_UNUSED);
		return res != 0;
	}

	bool StyleGetItalic(int style) const {
		int res = Call(SCI_STYLEGETITALIC, style, SCI_UNUSED);
		return res != 0;
	}

	int StyleGetSize(int style) const {
		int res = Call(SCI_STYLEGETSIZE, style, SCI_UNUSED);
		return res;
	}

	int StyleGetFont(int style, char* fontName) const {
		int res = Call(SCI_STYLEGETFONT, style, fontName);
		return res;
	}

	bool StyleGetEOLFilled(int style) const {
		int res = Call(SCI_STYLEGETEOLFILLED, style, SCI_UNUSED);
		return res != 0;
	}

	bool StyleGetUnderline(int style) const {
		int res = Call(SCI_STYLEGETUNDERLINE, style, SCI_UNUSED);
		return res != 0;
	}

	int StyleGetCase(int style) const {
		int res = Call(SCI_STYLEGETCASE, style, SCI_UNUSED);
		return res;
	}

	int StyleGetCharacterSet(int style) const {
		int res = Call(SCI_STYLEGETCHARACTERSET, style, SCI_UNUSED);
		return res;
	}

	bool StyleGetVisible(int style) const {
		int res = Call(SCI_STYLEGETVISIBLE, style, SCI_UNUSED);
		return res != 0;
	}

	bool StyleGetChangeable(int style) const {
		int res = Call(SCI_STYLEGETCHANGEABLE, style, SCI_UNUSED);
		return res != 0;
	}

	bool StyleGetHotSpot(int style) const {
		int res = Call(SCI_STYLEGETHOTSPOT, style, SCI_UNUSED);
		return res != 0;
	}

	void StyleSetCase(int style, int caseForce) const {
		Call(SCI_STYLESETCASE, style, caseForce);
	}

	void StyleSetSizeFractional(int style, int caseForce) const {
		Call(SCI_STYLESETSIZEFRACTIONAL, style, caseForce);
	}

	int StyleGetSizeFractional(int style) const {
		int res = Call(SCI_STYLEGETSIZEFRACTIONAL, style, SCI_UNUSED);
		return res;
	}

	void StyleSetWeight(int style, int weight) const {
		Call(SCI_STYLESETWEIGHT, style, weight);
	}

	int StyleGetWeight(int style) const {
		int res = Call(SCI_STYLEGETWEIGHT, style, SCI_UNUSED);
		return res;
	}

	void StyleSetCharacterSet(int style, int characterSet) const {
		Call(SCI_STYLESETCHARACTERSET, style, characterSet);
	}

	void StyleSetHotSpot(int style, bool hotspot) const {
		Call(SCI_STYLESETHOTSPOT, style, hotspot);
	}

	void SetSelFore(bool useSetting, int fore) const {
		Call(SCI_SETSELFORE, useSetting, fore);
	}

	void SetSelBack(bool useSetting, int back) const {
		Call(SCI_SETSELBACK, useSetting, back);
	}

	int GetSelAlpha() const {
		int res = Call(SCI_GETSELALPHA, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetSelAlpha(int alpha) const {
		Call(SCI_SETSELALPHA, alpha, SCI_UNUSED);
	}

	bool GetSelEOLFilled() const {
		int res = Call(SCI_GETSELEOLFILLED, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	void SetSelEOLFilled(bool filled) const {
		Call(SCI_SETSELEOLFILLED, filled, SCI_UNUSED);
	}

	void SetCaretFore(int fore) const {
		Call(SCI_SETCARETFORE, fore, SCI_UNUSED);
	}

	void AssignCmdKey(int km, int msg) const {
		Call(SCI_ASSIGNCMDKEY, km, msg);
	}

	void ClearCmdKey(int km) const {
		Call(SCI_CLEARCMDKEY, km, SCI_UNUSED);
	}

	void ClearAllCmdKeys() const {
		Call(SCI_CLEARALLCMDKEYS, SCI_UNUSED, SCI_UNUSED);
	}

	void SetStylingEx(int length, const char* styles) const {
		Call(SCI_SETSTYLINGEX, length, styles);
	}

	void StyleSetVisible(int style, bool visible) const {
		Call(SCI_STYLESETVISIBLE, style, visible);
	}

	int GetCaretPeriod() const {
		int res = Call(SCI_GETCARETPERIOD, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetCaretPeriod(int periodMilliseconds) const {
		Call(SCI_SETCARETPERIOD, periodMilliseconds, SCI_UNUSED);
	}

	void SetWordChars(const char* characters) const {
		Call(SCI_SETWORDCHARS, SCI_UNUSED, characters);
	}

	int GetWordChars(char* characters) const {
		int res = Call(SCI_GETWORDCHARS, SCI_UNUSED, characters);
		return res;
	}

	void BeginUndoAction() const {
		Call(SCI_BEGINUNDOACTION, SCI_UNUSED, SCI_UNUSED);
	}

	void EndUndoAction() const {
		Call(SCI_ENDUNDOACTION, SCI_UNUSED, SCI_UNUSED);
	}

	void IndicSetStyle(int indic, int style) const {
		Call(SCI_INDICSETSTYLE, indic, style);
	}

	int IndicGetStyle(int indic) const {
		int res = Call(SCI_INDICGETSTYLE, indic, SCI_UNUSED);
		return res;
	}

	void IndicSetFore(int indic, int fore) const {
		Call(SCI_INDICSETFORE, indic, fore);
	}

	int IndicGetFore(int indic) const {
		int res = Call(SCI_INDICGETFORE, indic, SCI_UNUSED);
		return res;
	}

	void IndicSetUnder(int indic, bool under) const {
		Call(SCI_INDICSETUNDER, indic, under);
	}

	bool IndicGetUnder(int indic) const {
		int res = Call(SCI_INDICGETUNDER, indic, SCI_UNUSED);
		return res != 0;
	}

	void IndicSetHoverStyle(int indic, int style) const {
		Call(SCI_INDICSETHOVERSTYLE, indic, style);
	}

	int IndicGetHoverStyle(int indic) const {
		int res = Call(SCI_INDICGETHOVERSTYLE, indic, SCI_UNUSED);
		return res;
	}

	void IndicSetHoverFore(int indic, int fore) const {
		Call(SCI_INDICSETHOVERFORE, indic, fore);
	}

	int IndicGetHoverFore(int indic) const {
		int res = Call(SCI_INDICGETHOVERFORE, indic, SCI_UNUSED);
		return res;
	}

	void IndicSetFlags(int indic, int flags) const {
		Call(SCI_INDICSETFLAGS, indic, flags);
	}

	int IndicGetFlags(int indic) const {
		int res = Call(SCI_INDICGETFLAGS, indic, SCI_UNUSED);
		return res;
	}

	void SetWhitespaceFore(bool useSetting, int fore) const {
		Call(SCI_SETWHITESPACEFORE, useSetting, fore);
	}

	void SetWhitespaceBack(bool useSetting, int back) const {
		Call(SCI_SETWHITESPACEBACK, useSetting, back);
	}

	void SetWhitespaceSize(int size) const {
		Call(SCI_SETWHITESPACESIZE, size, SCI_UNUSED);
	}

	int GetWhitespaceSize() const {
		int res = Call(SCI_GETWHITESPACESIZE, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetStyleBits(int bits) const {
		Call(SCI_SETSTYLEBITS, bits, SCI_UNUSED);
	}

	int GetStyleBits() const {
		int res = Call(SCI_GETSTYLEBITS, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetLineState(int line, int state) const {
		Call(SCI_SETLINESTATE, line, state);
	}

	int GetLineState(int line) const {
		int res = Call(SCI_GETLINESTATE, line, SCI_UNUSED);
		return res;
	}

	int GetMaxLineState() const {
		int res = Call(SCI_GETMAXLINESTATE, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	bool GetCaretLineVisible() const {
		int res = Call(SCI_GETCARETLINEVISIBLE, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	void SetCaretLineVisible(bool show) const {
		Call(SCI_SETCARETLINEVISIBLE, show, SCI_UNUSED);
	}

	int GetCaretLineBack() const {
		int res = Call(SCI_GETCARETLINEBACK, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetCaretLineBack(int back) const {
		Call(SCI_SETCARETLINEBACK, back, SCI_UNUSED);
	}

	void StyleSetChangeable(int style, bool changeable) const {
		Call(SCI_STYLESETCHANGEABLE, style, changeable);
	}

	void AutoCShow(int lenEntered, const char* itemList) const {
		Call(SCI_AUTOCSHOW, lenEntered, itemList);
	}

	void AutoCCancel() const {
		Call(SCI_AUTOCCANCEL, SCI_UNUSED, SCI_UNUSED);
	}

	bool AutoCActive() const {
		int res = Call(SCI_AUTOCACTIVE, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	int AutoCPosStart() const {
		int res = Call(SCI_AUTOCPOSSTART, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void AutoCComplete() const {
		Call(SCI_AUTOCCOMPLETE, SCI_UNUSED, SCI_UNUSED);
	}

	void AutoCStops(const char* characterSet) const {
		Call(SCI_AUTOCSTOPS, SCI_UNUSED, characterSet);
	}

	void AutoCSetSeparator(int separatorCharacter) const {
		Call(SCI_AUTOCSETSEPARATOR, separatorCharacter, SCI_UNUSED);
	}

	int AutoCGetSeparator() const {
		int res = Call(SCI_AUTOCGETSEPARATOR, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void AutoCSelect(const char* text) const {
		Call(SCI_AUTOCSELECT, SCI_UNUSED, text);
	}

	void AutoCSetCancelAtStart(bool cancel) const {
		Call(SCI_AUTOCSETCANCELATSTART, cancel, SCI_UNUSED);
	}

	bool AutoCGetCancelAtStart() const {
		int res = Call(SCI_AUTOCGETCANCELATSTART, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	void AutoCSetFillUps(const char* characterSet) const {
		Call(SCI_AUTOCSETFILLUPS, SCI_UNUSED, characterSet);
	}

	void AutoCSetChooseSingle(bool chooseSingle) const {
		Call(SCI_AUTOCSETCHOOSESINGLE, chooseSingle, SCI_UNUSED);
	}

	bool AutoCGetChooseSingle() const {
		int res = Call(SCI_AUTOCGETCHOOSESINGLE, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	void AutoCSetIgnoreCase(bool ignoreCase) const {
		Call(SCI_AUTOCSETIGNORECASE, ignoreCase, SCI_UNUSED);
	}

	bool AutoCGetIgnoreCase() const {
		int res = Call(SCI_AUTOCGETIGNORECASE, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	void UserListShow(int listType, const char* itemList) const {
		Call(SCI_USERLISTSHOW, listType, itemList);
	}

	void AutoCSetAutoHide(bool autoHide) const {
		Call(SCI_AUTOCSETAUTOHIDE, autoHide, SCI_UNUSED);
	}

	bool AutoCGetAutoHide() const {
		int res = Call(SCI_AUTOCGETAUTOHIDE, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	void AutoCSetDropRestOfWord(bool dropRestOfWord) const {
		Call(SCI_AUTOCSETDROPRESTOFWORD, dropRestOfWord, SCI_UNUSED);
	}

	bool AutoCGetDropRestOfWord() const {
		int res = Call(SCI_AUTOCGETDROPRESTOFWORD, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	void RegisterImage(int type, const char* xpmData) const {
		Call(SCI_REGISTERIMAGE, type, xpmData);
	}

	void ClearRegisteredImages() const {
		Call(SCI_CLEARREGISTEREDIMAGES, SCI_UNUSED, SCI_UNUSED);
	}

	int AutoCGetTypeSeparator() const {
		int res = Call(SCI_AUTOCGETTYPESEPARATOR, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void AutoCSetTypeSeparator(int separatorCharacter) const {
		Call(SCI_AUTOCSETTYPESEPARATOR, separatorCharacter, SCI_UNUSED);
	}

	void AutoCSetMaxWidth(int characterCount) const {
		Call(SCI_AUTOCSETMAXWIDTH, characterCount, SCI_UNUSED);
	}

	int AutoCGetMaxWidth() const {
		int res = Call(SCI_AUTOCGETMAXWIDTH, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void AutoCSetMaxHeight(int rowCount) const {
		Call(SCI_AUTOCSETMAXHEIGHT, rowCount, SCI_UNUSED);
	}

	int AutoCGetMaxHeight() const {
		int res = Call(SCI_AUTOCGETMAXHEIGHT, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetIndent(int indentSize) const {
		Call(SCI_SETINDENT, indentSize, SCI_UNUSED);
	}

	int GetIndent() const {
		int res = Call(SCI_GETINDENT, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetUseTabs(bool useTabs) const {
		Call(SCI_SETUSETABS, useTabs, SCI_UNUSED);
	}

	bool GetUseTabs() const {
		int res = Call(SCI_GETUSETABS, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	void SetLineIndentation(int line, int indentSize) const {
		Call(SCI_SETLINEINDENTATION, line, indentSize);
	}

	int GetLineIndentation(int line) const {
		int res = Call(SCI_GETLINEINDENTATION, line, SCI_UNUSED);
		return res;
	}

	int GetLineIndentPosition(int line) const {
		int res = Call(SCI_GETLINEINDENTPOSITION, line, SCI_UNUSED);
		return res;
	}

	int GetColumn(int pos) const {
		int res = Call(SCI_GETCOLUMN, pos, SCI_UNUSED);
		return res;
	}

	int CountCharacters(int startPos, int endPos) const {
		int res = Call(SCI_COUNTCHARACTERS, startPos, endPos);
		return res;
	}

	void SetHScrollBar(bool show) const {
		Call(SCI_SETHSCROLLBAR, show, SCI_UNUSED);
	}

	bool GetHScrollBar() const {
		int res = Call(SCI_GETHSCROLLBAR, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	void SetIndentationGuides(int indentView) const {
		Call(SCI_SETINDENTATIONGUIDES, indentView, SCI_UNUSED);
	}

	int GetIndentationGuides() const {
		int res = Call(SCI_GETINDENTATIONGUIDES, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetHighlightGuide(int column) const {
		Call(SCI_SETHIGHLIGHTGUIDE, column, SCI_UNUSED);
	}

	int GetHighlightGuide() const {
		int res = Call(SCI_GETHIGHLIGHTGUIDE, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	int GetLineEndPosition(int line) const {
		int res = Call(SCI_GETLINEENDPOSITION, line, SCI_UNUSED);
		return res;
	}

	int GetCodePage() const {
		int res = Call(SCI_GETCODEPAGE, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	int GetCaretFore() const {
		int res = Call(SCI_GETCARETFORE, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	bool GetReadOnly() const {
		int res = Call(SCI_GETREADONLY, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	void SetCurrentPos(int pos) const {
		Call(SCI_SETCURRENTPOS, pos, SCI_UNUSED);
	}

	void SetSelectionStart(int pos) const {
		Call(SCI_SETSELECTIONSTART, pos, SCI_UNUSED);
	}

	int GetSelectionStart() const {
		int res = Call(SCI_GETSELECTIONSTART, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetSelectionEnd(int pos) const {
		Call(SCI_SETSELECTIONEND, pos, SCI_UNUSED);
	}

	int GetSelectionEnd() const {
		int res = Call(SCI_GETSELECTIONEND, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetEmptySelection(int pos) const {
		Call(SCI_SETEMPTYSELECTION, pos, SCI_UNUSED);
	}

	void SetPrintMagnification(int magnification) const {
		Call(SCI_SETPRINTMAGNIFICATION, magnification, SCI_UNUSED);
	}

	int GetPrintMagnification() const {
		int res = Call(SCI_GETPRINTMAGNIFICATION, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetPrintColourMode(int mode) const {
		Call(SCI_SETPRINTCOLOURMODE, mode, SCI_UNUSED);
	}

	int GetPrintColourMode() const {
		int res = Call(SCI_GETPRINTCOLOURMODE, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	int FindText(int flags, Sci_TextToFind* ft) const {
		int res = Call(SCI_FINDTEXT, flags, ft);
		return res;
	}

	int FormatRange(bool draw, Sci_RangeToFormat* fr) const {
		int res = Call(SCI_FORMATRANGE, draw, fr);
		return res;
	}

	int GetFirstVisibleLine() const {
		int res = Call(SCI_GETFIRSTVISIBLELINE, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	int GetLine(int line, char* text) const {
		int res = Call(SCI_GETLINE, line, text);
		return res;
	}

	int GetLineCount() const {
		int res = Call(SCI_GETLINECOUNT, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetMarginLeft(int pixelWidth) const {
		Call(SCI_SETMARGINLEFT, SCI_UNUSED, pixelWidth);
	}

	int GetMarginLeft() const {
		int res = Call(SCI_GETMARGINLEFT, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetMarginRight(int pixelWidth) const {
		Call(SCI_SETMARGINRIGHT, SCI_UNUSED, pixelWidth);
	}

	int GetMarginRight() const {
		int res = Call(SCI_GETMARGINRIGHT, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	bool GetModify() const {
		int res = Call(SCI_GETMODIFY, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	void SetSel(int start, int end) const {
		Call(SCI_SETSEL, start, end);
	}

	int GetSelText(char* text) const {
		int res = Call(SCI_GETSELTEXT, SCI_UNUSED, text);
		return res;
	}

	int GetTextRange(Sci_TextRange* tr) const {
		int res = Call(SCI_GETTEXTRANGE, SCI_UNUSED, tr);
		return res;
	}

	void HideSelection(bool normal) const {
		Call(SCI_HIDESELECTION, normal, SCI_UNUSED);
	}

	int PointXFromPosition(int pos) const {
		int res = Call(SCI_POINTXFROMPOSITION, SCI_UNUSED, pos);
		return res;
	}

	int PointYFromPosition(int pos) const {
		int res = Call(SCI_POINTYFROMPOSITION, SCI_UNUSED, pos);
		return res;
	}

	int LineFromPosition(int pos) const {
		int res = Call(SCI_LINEFROMPOSITION, pos, SCI_UNUSED);
		return res;
	}

	int PositionFromLine(int line) const {
		int res = Call(SCI_POSITIONFROMLINE, line, SCI_UNUSED);
		return res;
	}

	void LineScroll(int columns, int lines) const {
		Call(SCI_LINESCROLL, columns, lines);
	}

	void ScrollCaret() const {
		Call(SCI_SCROLLCARET, SCI_UNUSED, SCI_UNUSED);
	}

	void ScrollRange(int secondary, int primary) const {
		Call(SCI_SCROLLRANGE, secondary, primary);
	}

	void ReplaceSel(const char* text) const {
		Call(SCI_REPLACESEL, SCI_UNUSED, text);
	}

	void SetReadOnly(bool readOnly) const {
		Call(SCI_SETREADONLY, readOnly, SCI_UNUSED);
	}

	void Null() const {
		Call(SCI_NULL, SCI_UNUSED, SCI_UNUSED);
	}

	bool CanPaste() const {
		int res = Call(SCI_CANPASTE, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	bool CanUndo() const {
		int res = Call(SCI_CANUNDO, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	void EmptyUndoBuffer() const {
		Call(SCI_EMPTYUNDOBUFFER, SCI_UNUSED, SCI_UNUSED);
	}

	void Undo() const {
		Call(SCI_UNDO, SCI_UNUSED, SCI_UNUSED);
	}

	void Cut() const {
		Call(SCI_CUT, SCI_UNUSED, SCI_UNUSED);
	}

	void Copy() const {
		Call(SCI_COPY, SCI_UNUSED, SCI_UNUSED);
	}

	void Paste() const {
		Call(SCI_PASTE, SCI_UNUSED, SCI_UNUSED);
	}

	void Clear() const {
		Call(SCI_CLEAR, SCI_UNUSED, SCI_UNUSED);
	}

	void SetText(const char* text) const {
		Call(SCI_SETTEXT, SCI_UNUSED, text);
	}

	int GetText(int length, char* text) const {
		int res = Call(SCI_GETTEXT, length, text);
		return res;
	}

	int GetTextLength() const {
		int res = Call(SCI_GETTEXTLENGTH, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	int GetDirectFunction() const {
		int res = Call(SCI_GETDIRECTFUNCTION, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	int GetDirectPointer() const {
		int res = Call(SCI_GETDIRECTPOINTER, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetOvertype(bool overtype) const {
		Call(SCI_SETOVERTYPE, overtype, SCI_UNUSED);
	}

	bool GetOvertype() const {
		int res = Call(SCI_GETOVERTYPE, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	void SetCaretWidth(int pixelWidth) const {
		Call(SCI_SETCARETWIDTH, pixelWidth, SCI_UNUSED);
	}

	int GetCaretWidth() const {
		int res = Call(SCI_GETCARETWIDTH, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetTargetStart(int pos) const {
		Call(SCI_SETTARGETSTART, pos, SCI_UNUSED);
	}

	int GetTargetStart() const {
		int res = Call(SCI_GETTARGETSTART, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetTargetEnd(int pos) const {
		Call(SCI_SETTARGETEND, pos, SCI_UNUSED);
	}

	int GetTargetEnd() const {
		int res = Call(SCI_GETTARGETEND, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetTargetRange(int start, int end) const {
		Call(SCI_SETTARGETRANGE, start, end);
	}

	int GetTargetText(char* characters) const {
		int res = Call(SCI_GETTARGETTEXT, SCI_UNUSED, characters);
		return res;
	}

	int ReplaceTarget(int length, const char* text) const {
		int res = Call(SCI_REPLACETARGET, length, text);
		return res;
	}

	int ReplaceTargetRE(int length, const char* text) const {
		int res = Call(SCI_REPLACETARGETRE, length, text);
		return res;
	}

	int SearchInTarget(int length, const char* text) const {
		int res = Call(SCI_SEARCHINTARGET, length, text);
		return res;
	}

	void SetSearchFlags(int flags) const {
		Call(SCI_SETSEARCHFLAGS, flags, SCI_UNUSED);
	}

	int GetSearchFlags() const {
		int res = Call(SCI_GETSEARCHFLAGS, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void CallTipShow(int pos, const char* definition) const {
		Call(SCI_CALLTIPSHOW, pos, definition);
	}

	void CallTipCancel() const {
		Call(SCI_CALLTIPCANCEL, SCI_UNUSED, SCI_UNUSED);
	}

	bool CallTipActive() const {
		int res = Call(SCI_CALLTIPACTIVE, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	int CallTipPosStart() const {
		int res = Call(SCI_CALLTIPPOSSTART, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void CallTipSetPosStart(int posStart) const {
		Call(SCI_CALLTIPSETPOSSTART, posStart, SCI_UNUSED);
	}

	void CallTipSetHlt(int start, int end) const {
		Call(SCI_CALLTIPSETHLT, start, end);
	}

	void CallTipSetBack(int back) const {
		Call(SCI_CALLTIPSETBACK, back, SCI_UNUSED);
	}

	void CallTipSetFore(int fore) const {
		Call(SCI_CALLTIPSETFORE, fore, SCI_UNUSED);
	}

	void CallTipSetForeHlt(int fore) const {
		Call(SCI_CALLTIPSETFOREHLT, fore, SCI_UNUSED);
	}

	void CallTipUseStyle(int tabSize) const {
		Call(SCI_CALLTIPUSESTYLE, tabSize, SCI_UNUSED);
	}

	void CallTipSetPosition(bool above) const {
		Call(SCI_CALLTIPSETPOSITION, above, SCI_UNUSED);
	}

	int VisibleFromDocLine(int line) const {
		int res = Call(SCI_VISIBLEFROMDOCLINE, line, SCI_UNUSED);
		return res;
	}

	int DocLineFromVisible(int lineDisplay) const {
		int res = Call(SCI_DOCLINEFROMVISIBLE, lineDisplay, SCI_UNUSED);
		return res;
	}

	int WrapCount(int line) const {
		int res = Call(SCI_WRAPCOUNT, line, SCI_UNUSED);
		return res;
	}

	void SetFoldLevel(int line, int level) const {
		Call(SCI_SETFOLDLEVEL, line, level);
	}

	int GetFoldLevel(int line) const {
		int res = Call(SCI_GETFOLDLEVEL, line, SCI_UNUSED);
		return res;
	}

	int GetLastChild(int line, int level) const {
		int res = Call(SCI_GETLASTCHILD, line, level);
		return res;
	}

	int GetFoldParent(int line) const {
		int res = Call(SCI_GETFOLDPARENT, line, SCI_UNUSED);
		return res;
	}

	void ShowLines(int lineStart, int lineEnd) const {
		Call(SCI_SHOWLINES, lineStart, lineEnd);
	}

	void HideLines(int lineStart, int lineEnd) const {
		Call(SCI_HIDELINES, lineStart, lineEnd);
	}

	bool GetLineVisible(int line) const {
		int res = Call(SCI_GETLINEVISIBLE, line, SCI_UNUSED);
		return res != 0;
	}

	bool GetAllLinesVisible() const {
		int res = Call(SCI_GETALLLINESVISIBLE, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	void SetFoldExpanded(int line, bool expanded) const {
		Call(SCI_SETFOLDEXPANDED, line, expanded);
	}

	bool GetFoldExpanded(int line) const {
		int res = Call(SCI_GETFOLDEXPANDED, line, SCI_UNUSED);
		return res != 0;
	}

	void ToggleFold(int line) const {
		Call(SCI_TOGGLEFOLD, line, SCI_UNUSED);
	}

	void FoldLine(int line, int action) const {
		Call(SCI_FOLDLINE, line, action);
	}

	void FoldChildren(int line, int action) const {
		Call(SCI_FOLDCHILDREN, line, action);
	}

	void ExpandChildren(int line, int level) const {
		Call(SCI_EXPANDCHILDREN, line, level);
	}

	void FoldAll(int action) const {
		Call(SCI_FOLDALL, action, SCI_UNUSED);
	}

	void EnsureVisible(int line) const {
		Call(SCI_ENSUREVISIBLE, line, SCI_UNUSED);
	}

	void SetAutomaticFold(int automaticFold) const {
		Call(SCI_SETAUTOMATICFOLD, automaticFold, SCI_UNUSED);
	}

	int GetAutomaticFold() const {
		int res = Call(SCI_GETAUTOMATICFOLD, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetFoldFlags(int flags) const {
		Call(SCI_SETFOLDFLAGS, flags, SCI_UNUSED);
	}

	void EnsureVisibleEnforcePolicy(int line) const {
		Call(SCI_ENSUREVISIBLEENFORCEPOLICY, line, SCI_UNUSED);
	}

	void SetTabIndents(bool tabIndents) const {
		Call(SCI_SETTABINDENTS, tabIndents, SCI_UNUSED);
	}

	bool GetTabIndents() const {
		int res = Call(SCI_GETTABINDENTS, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	void SetBackSpaceUnIndents(bool bsUnIndents) const {
		Call(SCI_SETBACKSPACEUNINDENTS, bsUnIndents, SCI_UNUSED);
	}

	bool GetBackSpaceUnIndents() const {
		int res = Call(SCI_GETBACKSPACEUNINDENTS, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	void SetMouseDwellTime(int periodMilliseconds) const {
		Call(SCI_SETMOUSEDWELLTIME, periodMilliseconds, SCI_UNUSED);
	}

	int GetMouseDwellTime() const {
		int res = Call(SCI_GETMOUSEDWELLTIME, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	int WordStartPosition(int pos, bool onlyWordCharacters) const {
		int res = Call(SCI_WORDSTARTPOSITION, pos, onlyWordCharacters);
		return res;
	}

	int WordEndPosition(int pos, bool onlyWordCharacters) const {
		int res = Call(SCI_WORDENDPOSITION, pos, onlyWordCharacters);
		return res;
	}

	void SetWrapMode(int mode) const {
		Call(SCI_SETWRAPMODE, mode, SCI_UNUSED);
	}

	int GetWrapMode() const {
		int res = Call(SCI_GETWRAPMODE, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetWrapVisualFlags(int wrapVisualFlags) const {
		Call(SCI_SETWRAPVISUALFLAGS, wrapVisualFlags, SCI_UNUSED);
	}

	int GetWrapVisualFlags() const {
		int res = Call(SCI_GETWRAPVISUALFLAGS, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetWrapVisualFlagsLocation(int wrapVisualFlagsLocation) const {
		Call(SCI_SETWRAPVISUALFLAGSLOCATION, wrapVisualFlagsLocation, SCI_UNUSED);
	}

	int GetWrapVisualFlagsLocation() const {
		int res = Call(SCI_GETWRAPVISUALFLAGSLOCATION, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetWrapStartIndent(int indent) const {
		Call(SCI_SETWRAPSTARTINDENT, indent, SCI_UNUSED);
	}

	int GetWrapStartIndent() const {
		int res = Call(SCI_GETWRAPSTARTINDENT, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetWrapIndentMode(int mode) const {
		Call(SCI_SETWRAPINDENTMODE, mode, SCI_UNUSED);
	}

	int GetWrapIndentMode() const {
		int res = Call(SCI_GETWRAPINDENTMODE, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetLayoutCache(int mode) const {
		Call(SCI_SETLAYOUTCACHE, mode, SCI_UNUSED);
	}

	int GetLayoutCache() const {
		int res = Call(SCI_GETLAYOUTCACHE, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetScrollWidth(int pixelWidth) const {
		Call(SCI_SETSCROLLWIDTH, pixelWidth, SCI_UNUSED);
	}

	int GetScrollWidth() const {
		int res = Call(SCI_GETSCROLLWIDTH, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetScrollWidthTracking(bool tracking) const {
		Call(SCI_SETSCROLLWIDTHTRACKING, tracking, SCI_UNUSED);
	}

	bool GetScrollWidthTracking() const {
		int res = Call(SCI_GETSCROLLWIDTHTRACKING, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	int TextWidth(int style, const char* text) const {
		int res = Call(SCI_TEXTWIDTH, style, text);
		return res;
	}

	void SetEndAtLastLine(bool endAtLastLine) const {
		Call(SCI_SETENDATLASTLINE, endAtLastLine, SCI_UNUSED);
	}

	bool GetEndAtLastLine() const {
		int res = Call(SCI_GETENDATLASTLINE, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	int TextHeight(int line) const {
		int res = Call(SCI_TEXTHEIGHT, line, SCI_UNUSED);
		return res;
	}

	void SetVScrollBar(bool show) const {
		Call(SCI_SETVSCROLLBAR, show, SCI_UNUSED);
	}

	bool GetVScrollBar() const {
		int res = Call(SCI_GETVSCROLLBAR, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	void AppendText(int length, const char* text) const {
		Call(SCI_APPENDTEXT, length, text);
	}

	bool GetTwoPhaseDraw() const {
		int res = Call(SCI_GETTWOPHASEDRAW, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	void SetTwoPhaseDraw(bool twoPhase) const {
		Call(SCI_SETTWOPHASEDRAW, twoPhase, SCI_UNUSED);
	}

	int GetPhasesDraw() const {
		int res = Call(SCI_GETPHASESDRAW, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetPhasesDraw(int phases) const {
		Call(SCI_SETPHASESDRAW, phases, SCI_UNUSED);
	}

	void SetFontQuality(int fontQuality) const {
		Call(SCI_SETFONTQUALITY, fontQuality, SCI_UNUSED);
	}

	int GetFontQuality() const {
		int res = Call(SCI_GETFONTQUALITY, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetFirstVisibleLine(int lineDisplay) const {
		Call(SCI_SETFIRSTVISIBLELINE, lineDisplay, SCI_UNUSED);
	}

	void SetMultiPaste(int multiPaste) const {
		Call(SCI_SETMULTIPASTE, multiPaste, SCI_UNUSED);
	}

	int GetMultiPaste() const {
		int res = Call(SCI_GETMULTIPASTE, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	int GetTag(int tagNumber, char* tagValue) const {
		int res = Call(SCI_GETTAG, tagNumber, tagValue);
		return res;
	}

	void TargetFromSelection() const {
		Call(SCI_TARGETFROMSELECTION, SCI_UNUSED, SCI_UNUSED);
	}

	void LinesJoin() const {
		Call(SCI_LINESJOIN, SCI_UNUSED, SCI_UNUSED);
	}

	void LinesSplit(int pixelWidth) const {
		Call(SCI_LINESSPLIT, pixelWidth, SCI_UNUSED);
	}

	void SetFoldMarginColour(bool useSetting, int back) const {
		Call(SCI_SETFOLDMARGINCOLOUR, useSetting, back);
	}

	void SetFoldMarginHiColour(bool useSetting, int fore) const {
		Call(SCI_SETFOLDMARGINHICOLOUR, useSetting, fore);
	}

	void LineDown() const {
		Call(SCI_LINEDOWN, SCI_UNUSED, SCI_UNUSED);
	}

	void LineDownExtend() const {
		Call(SCI_LINEDOWNEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void LineUp() const {
		Call(SCI_LINEUP, SCI_UNUSED, SCI_UNUSED);
	}

	void LineUpExtend() const {
		Call(SCI_LINEUPEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void CharLeft() const {
		Call(SCI_CHARLEFT, SCI_UNUSED, SCI_UNUSED);
	}

	void CharLeftExtend() const {
		Call(SCI_CHARLEFTEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void CharRight() const {
		Call(SCI_CHARRIGHT, SCI_UNUSED, SCI_UNUSED);
	}

	void CharRightExtend() const {
		Call(SCI_CHARRIGHTEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void WordLeft() const {
		Call(SCI_WORDLEFT, SCI_UNUSED, SCI_UNUSED);
	}

	void WordLeftExtend() const {
		Call(SCI_WORDLEFTEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void WordRight() const {
		Call(SCI_WORDRIGHT, SCI_UNUSED, SCI_UNUSED);
	}

	void WordRightExtend() const {
		Call(SCI_WORDRIGHTEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void Home() const {
		Call(SCI_HOME, SCI_UNUSED, SCI_UNUSED);
	}

	void HomeExtend() const {
		Call(SCI_HOMEEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void LineEnd() const {
		Call(SCI_LINEEND, SCI_UNUSED, SCI_UNUSED);
	}

	void LineEndExtend() const {
		Call(SCI_LINEENDEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void DocumentStart() const {
		Call(SCI_DOCUMENTSTART, SCI_UNUSED, SCI_UNUSED);
	}

	void DocumentStartExtend() const {
		Call(SCI_DOCUMENTSTARTEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void DocumentEnd() const {
		Call(SCI_DOCUMENTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void DocumentEndExtend() const {
		Call(SCI_DOCUMENTENDEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void PageUp() const {
		Call(SCI_PAGEUP, SCI_UNUSED, SCI_UNUSED);
	}

	void PageUpExtend() const {
		Call(SCI_PAGEUPEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void PageDown() const {
		Call(SCI_PAGEDOWN, SCI_UNUSED, SCI_UNUSED);
	}

	void PageDownExtend() const {
		Call(SCI_PAGEDOWNEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void EditToggleOvertype() const {
		Call(SCI_EDITTOGGLEOVERTYPE, SCI_UNUSED, SCI_UNUSED);
	}

	void Cancel() const {
		Call(SCI_CANCEL, SCI_UNUSED, SCI_UNUSED);
	}

	void DeleteBack() const {
		Call(SCI_DELETEBACK, SCI_UNUSED, SCI_UNUSED);
	}

	void Tab() const {
		Call(SCI_TAB, SCI_UNUSED, SCI_UNUSED);
	}

	void BackTab() const {
		Call(SCI_BACKTAB, SCI_UNUSED, SCI_UNUSED);
	}

	void NewLine() const {
		Call(SCI_NEWLINE, SCI_UNUSED, SCI_UNUSED);
	}

	void FormFeed() const {
		Call(SCI_FORMFEED, SCI_UNUSED, SCI_UNUSED);
	}

	void VCHome() const {
		Call(SCI_VCHOME, SCI_UNUSED, SCI_UNUSED);
	}

	void VCHomeExtend() const {
		Call(SCI_VCHOMEEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void ZoomIn() const {
		Call(SCI_ZOOMIN, SCI_UNUSED, SCI_UNUSED);
	}

	void ZoomOut() const {
		Call(SCI_ZOOMOUT, SCI_UNUSED, SCI_UNUSED);
	}

	void DelWordLeft() const {
		Call(SCI_DELWORDLEFT, SCI_UNUSED, SCI_UNUSED);
	}

	void DelWordRight() const {
		Call(SCI_DELWORDRIGHT, SCI_UNUSED, SCI_UNUSED);
	}

	void DelWordRightEnd() const {
		Call(SCI_DELWORDRIGHTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void LineCut() const {
		Call(SCI_LINECUT, SCI_UNUSED, SCI_UNUSED);
	}

	void LineDelete() const {
		Call(SCI_LINEDELETE, SCI_UNUSED, SCI_UNUSED);
	}

	void LineTranspose() const {
		Call(SCI_LINETRANSPOSE, SCI_UNUSED, SCI_UNUSED);
	}

	void LineDuplicate() const {
		Call(SCI_LINEDUPLICATE, SCI_UNUSED, SCI_UNUSED);
	}

	void LowerCase() const {
		Call(SCI_LOWERCASE, SCI_UNUSED, SCI_UNUSED);
	}

	void UpperCase() const {
		Call(SCI_UPPERCASE, SCI_UNUSED, SCI_UNUSED);
	}

	void LineScrollDown() const {
		Call(SCI_LINESCROLLDOWN, SCI_UNUSED, SCI_UNUSED);
	}

	void LineScrollUp() const {
		Call(SCI_LINESCROLLUP, SCI_UNUSED, SCI_UNUSED);
	}

	void DeleteBackNotLine() const {
		Call(SCI_DELETEBACKNOTLINE, SCI_UNUSED, SCI_UNUSED);
	}

	void HomeDisplay() const {
		Call(SCI_HOMEDISPLAY, SCI_UNUSED, SCI_UNUSED);
	}

	void HomeDisplayExtend() const {
		Call(SCI_HOMEDISPLAYEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void LineEndDisplay() const {
		Call(SCI_LINEENDDISPLAY, SCI_UNUSED, SCI_UNUSED);
	}

	void LineEndDisplayExtend() const {
		Call(SCI_LINEENDDISPLAYEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void HomeWrap() const {
		Call(SCI_HOMEWRAP, SCI_UNUSED, SCI_UNUSED);
	}

	void HomeWrapExtend() const {
		Call(SCI_HOMEWRAPEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void LineEndWrap() const {
		Call(SCI_LINEENDWRAP, SCI_UNUSED, SCI_UNUSED);
	}

	void LineEndWrapExtend() const {
		Call(SCI_LINEENDWRAPEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void VCHomeWrap() const {
		Call(SCI_VCHOMEWRAP, SCI_UNUSED, SCI_UNUSED);
	}

	void VCHomeWrapExtend() const {
		Call(SCI_VCHOMEWRAPEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void LineCopy() const {
		Call(SCI_LINECOPY, SCI_UNUSED, SCI_UNUSED);
	}

	void MoveCaretInsideView() const {
		Call(SCI_MOVECARETINSIDEVIEW, SCI_UNUSED, SCI_UNUSED);
	}

	int LineLength(int line) const {
		int res = Call(SCI_LINELENGTH, line, SCI_UNUSED);
		return res;
	}

	void BraceHighlight(int pos1, int pos2) const {
		Call(SCI_BRACEHIGHLIGHT, pos1, pos2);
	}

	void BraceHighlightIndicator(bool useBraceHighlightIndicator, int indicator) const {
		Call(SCI_BRACEHIGHLIGHTINDICATOR, useBraceHighlightIndicator, indicator);
	}

	void BraceBadLight(int pos) const {
		Call(SCI_BRACEBADLIGHT, pos, SCI_UNUSED);
	}

	void BraceBadLightIndicator(bool useBraceBadLightIndicator, int indicator) const {
		Call(SCI_BRACEBADLIGHTINDICATOR, useBraceBadLightIndicator, indicator);
	}

	int BraceMatch(int pos) const {
		int res = Call(SCI_BRACEMATCH, pos, SCI_UNUSED);
		return res;
	}

	bool GetViewEOL() const {
		int res = Call(SCI_GETVIEWEOL, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	void SetViewEOL(bool visible) const {
		Call(SCI_SETVIEWEOL, visible, SCI_UNUSED);
	}

	int GetDocPointer() const {
		int res = Call(SCI_GETDOCPOINTER, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetDocPointer(int pointer) const {
		Call(SCI_SETDOCPOINTER, SCI_UNUSED, pointer);
	}

	void SetModEventMask(int mask) const {
		Call(SCI_SETMODEVENTMASK, mask, SCI_UNUSED);
	}

	int GetEdgeColumn() const {
		int res = Call(SCI_GETEDGECOLUMN, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetEdgeColumn(int column) const {
		Call(SCI_SETEDGECOLUMN, column, SCI_UNUSED);
	}

	int GetEdgeMode() const {
		int res = Call(SCI_GETEDGEMODE, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetEdgeMode(int mode) const {
		Call(SCI_SETEDGEMODE, mode, SCI_UNUSED);
	}

	int GetEdgeColour() const {
		int res = Call(SCI_GETEDGECOLOUR, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetEdgeColour(int edgeColour) const {
		Call(SCI_SETEDGECOLOUR, edgeColour, SCI_UNUSED);
	}

	void SearchAnchor() const {
		Call(SCI_SEARCHANCHOR, SCI_UNUSED, SCI_UNUSED);
	}

	int SearchNext(int flags, const char* text) const {
		int res = Call(SCI_SEARCHNEXT, flags, text);
		return res;
	}

	int SearchPrev(int flags, const char* text) const {
		int res = Call(SCI_SEARCHPREV, flags, text);
		return res;
	}

	int LinesOnScreen() const {
		int res = Call(SCI_LINESONSCREEN, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void UsePopUp(bool allowPopUp) const {
		Call(SCI_USEPOPUP, allowPopUp, SCI_UNUSED);
	}

	bool SelectionIsRectangle() const {
		int res = Call(SCI_SELECTIONISRECTANGLE, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	void SetZoom(int zoom) const {
		Call(SCI_SETZOOM, zoom, SCI_UNUSED);
	}

	int GetZoom() const {
		int res = Call(SCI_GETZOOM, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	int CreateDocument() const {
		int res = Call(SCI_CREATEDOCUMENT, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void AddRefDocument(int doc) const {
		Call(SCI_ADDREFDOCUMENT, SCI_UNUSED, doc);
	}

	void ReleaseDocument(int doc) const {
		Call(SCI_RELEASEDOCUMENT, SCI_UNUSED, doc);
	}

	int GetModEventMask() const {
		int res = Call(SCI_GETMODEVENTMASK, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetFocus(bool focus) const {
		Call(SCI_SETFOCUS, focus, SCI_UNUSED);
	}

	bool GetFocus() const {
		int res = Call(SCI_GETFOCUS, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	void SetStatus(int statusCode) const {
		Call(SCI_SETSTATUS, statusCode, SCI_UNUSED);
	}

	int GetStatus() const {
		int res = Call(SCI_GETSTATUS, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetMouseDownCaptures(bool captures) const {
		Call(SCI_SETMOUSEDOWNCAPTURES, captures, SCI_UNUSED);
	}

	bool GetMouseDownCaptures() const {
		int res = Call(SCI_GETMOUSEDOWNCAPTURES, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	void SetCursor(int cursorType) const {
		Call(SCI_SETCURSOR, cursorType, SCI_UNUSED);
	}

	int GetCursor() const {
		int res = Call(SCI_GETCURSOR, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetControlCharSymbol(int symbol) const {
		Call(SCI_SETCONTROLCHARSYMBOL, symbol, SCI_UNUSED);
	}

	int GetControlCharSymbol() const {
		int res = Call(SCI_GETCONTROLCHARSYMBOL, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void WordPartLeft() const {
		Call(SCI_WORDPARTLEFT, SCI_UNUSED, SCI_UNUSED);
	}

	void WordPartLeftExtend() const {
		Call(SCI_WORDPARTLEFTEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void WordPartRight() const {
		Call(SCI_WORDPARTRIGHT, SCI_UNUSED, SCI_UNUSED);
	}

	void WordPartRightExtend() const {
		Call(SCI_WORDPARTRIGHTEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void SetVisiblePolicy(int visiblePolicy, int visibleSlop) const {
		Call(SCI_SETVISIBLEPOLICY, visiblePolicy, visibleSlop);
	}

	void DelLineLeft() const {
		Call(SCI_DELLINELEFT, SCI_UNUSED, SCI_UNUSED);
	}

	void DelLineRight() const {
		Call(SCI_DELLINERIGHT, SCI_UNUSED, SCI_UNUSED);
	}

	void SetXOffset(int newOffset) const {
		Call(SCI_SETXOFFSET, newOffset, SCI_UNUSED);
	}

	int GetXOffset() const {
		int res = Call(SCI_GETXOFFSET, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void ChooseCaretX() const {
		Call(SCI_CHOOSECARETX, SCI_UNUSED, SCI_UNUSED);
	}

	void GrabFocus() const {
		Call(SCI_GRABFOCUS, SCI_UNUSED, SCI_UNUSED);
	}

	void SetXCaretPolicy(int caretPolicy, int caretSlop) const {
		Call(SCI_SETXCARETPOLICY, caretPolicy, caretSlop);
	}

	void SetYCaretPolicy(int caretPolicy, int caretSlop) const {
		Call(SCI_SETYCARETPOLICY, caretPolicy, caretSlop);
	}

	void SetPrintWrapMode(int mode) const {
		Call(SCI_SETPRINTWRAPMODE, mode, SCI_UNUSED);
	}

	int GetPrintWrapMode() const {
		int res = Call(SCI_GETPRINTWRAPMODE, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetHotspotActiveFore(bool useSetting, int fore) const {
		Call(SCI_SETHOTSPOTACTIVEFORE, useSetting, fore);
	}

	int GetHotspotActiveFore() const {
		int res = Call(SCI_GETHOTSPOTACTIVEFORE, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetHotspotActiveBack(bool useSetting, int back) const {
		Call(SCI_SETHOTSPOTACTIVEBACK, useSetting, back);
	}

	int GetHotspotActiveBack() const {
		int res = Call(SCI_GETHOTSPOTACTIVEBACK, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetHotspotActiveUnderline(bool underline) const {
		Call(SCI_SETHOTSPOTACTIVEUNDERLINE, underline, SCI_UNUSED);
	}

	bool GetHotspotActiveUnderline() const {
		int res = Call(SCI_GETHOTSPOTACTIVEUNDERLINE, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	void SetHotspotSingleLine(bool singleLine) const {
		Call(SCI_SETHOTSPOTSINGLELINE, singleLine, SCI_UNUSED);
	}

	bool GetHotspotSingleLine() const {
		int res = Call(SCI_GETHOTSPOTSINGLELINE, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	void ParaDown() const {
		Call(SCI_PARADOWN, SCI_UNUSED, SCI_UNUSED);
	}

	void ParaDownExtend() const {
		Call(SCI_PARADOWNEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void ParaUp() const {
		Call(SCI_PARAUP, SCI_UNUSED, SCI_UNUSED);
	}

	void ParaUpExtend() const {
		Call(SCI_PARAUPEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	int PositionBefore(int pos) const {
		int res = Call(SCI_POSITIONBEFORE, pos, SCI_UNUSED);
		return res;
	}

	int PositionAfter(int pos) const {
		int res = Call(SCI_POSITIONAFTER, pos, SCI_UNUSED);
		return res;
	}

	int PositionRelative(int pos, int relative) const {
		int res = Call(SCI_POSITIONRELATIVE, pos, relative);
		return res;
	}

	void CopyRange(int start, int end) const {
		Call(SCI_COPYRANGE, start, end);
	}

	void CopyText(int length, const char* text) const {
		Call(SCI_COPYTEXT, length, text);
	}

	void SetSelectionMode(int mode) const {
		Call(SCI_SETSELECTIONMODE, mode, SCI_UNUSED);
	}

	int GetSelectionMode() const {
		int res = Call(SCI_GETSELECTIONMODE, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	int GetLineSelStartPosition(int line) const {
		int res = Call(SCI_GETLINESELSTARTPOSITION, line, SCI_UNUSED);
		return res;
	}

	int GetLineSelEndPosition(int line) const {
		int res = Call(SCI_GETLINESELENDPOSITION, line, SCI_UNUSED);
		return res;
	}

	void LineDownRectExtend() const {
		Call(SCI_LINEDOWNRECTEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void LineUpRectExtend() const {
		Call(SCI_LINEUPRECTEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void CharLeftRectExtend() const {
		Call(SCI_CHARLEFTRECTEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void CharRightRectExtend() const {
		Call(SCI_CHARRIGHTRECTEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void HomeRectExtend() const {
		Call(SCI_HOMERECTEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void VCHomeRectExtend() const {
		Call(SCI_VCHOMERECTEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void LineEndRectExtend() const {
		Call(SCI_LINEENDRECTEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void PageUpRectExtend() const {
		Call(SCI_PAGEUPRECTEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void PageDownRectExtend() const {
		Call(SCI_PAGEDOWNRECTEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void StutteredPageUp() const {
		Call(SCI_STUTTEREDPAGEUP, SCI_UNUSED, SCI_UNUSED);
	}

	void StutteredPageUpExtend() const {
		Call(SCI_STUTTEREDPAGEUPEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void StutteredPageDown() const {
		Call(SCI_STUTTEREDPAGEDOWN, SCI_UNUSED, SCI_UNUSED);
	}

	void StutteredPageDownExtend() const {
		Call(SCI_STUTTEREDPAGEDOWNEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void WordLeftEnd() const {
		Call(SCI_WORDLEFTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void WordLeftEndExtend() const {
		Call(SCI_WORDLEFTENDEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void WordRightEnd() const {
		Call(SCI_WORDRIGHTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void WordRightEndExtend() const {
		Call(SCI_WORDRIGHTENDEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	void SetWhitespaceChars(const char* characters) const {
		Call(SCI_SETWHITESPACECHARS, SCI_UNUSED, characters);
	}

	int GetWhitespaceChars(char* characters) const {
		int res = Call(SCI_GETWHITESPACECHARS, SCI_UNUSED, characters);
		return res;
	}

	void SetPunctuationChars(const char* characters) const {
		Call(SCI_SETPUNCTUATIONCHARS, SCI_UNUSED, characters);
	}

	int GetPunctuationChars(char* characters) const {
		int res = Call(SCI_GETPUNCTUATIONCHARS, SCI_UNUSED, characters);
		return res;
	}

	void SetCharsDefault() const {
		Call(SCI_SETCHARSDEFAULT, SCI_UNUSED, SCI_UNUSED);
	}

	int AutoCGetCurrent() const {
		int res = Call(SCI_AUTOCGETCURRENT, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	int AutoCGetCurrentText(char* s) const {
		int res = Call(SCI_AUTOCGETCURRENTTEXT, SCI_UNUSED, s);
		return res;
	}

	void AutoCSetCaseInsensitiveBehaviour(int behaviour) const {
		Call(SCI_AUTOCSETCASEINSENSITIVEBEHAVIOUR, behaviour, SCI_UNUSED);
	}

	int AutoCGetCaseInsensitiveBehaviour() const {
		int res = Call(SCI_AUTOCGETCASEINSENSITIVEBEHAVIOUR, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void AutoCSetMulti(int multi) const {
		Call(SCI_AUTOCSETMULTI, multi, SCI_UNUSED);
	}

	int AutoCGetMulti() const {
		int res = Call(SCI_AUTOCGETMULTI, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void AutoCSetOrder(int order) const {
		Call(SCI_AUTOCSETORDER, order, SCI_UNUSED);
	}

	int AutoCGetOrder() const {
		int res = Call(SCI_AUTOCGETORDER, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void Allocate(int bytes) const {
		Call(SCI_ALLOCATE, bytes, SCI_UNUSED);
	}

	int TargetAsUTF8(char* s) const {
		int res = Call(SCI_TARGETASUTF8, SCI_UNUSED, s);
		return res;
	}

	void SetLengthForEncode(int bytes) const {
		Call(SCI_SETLENGTHFORENCODE, bytes, SCI_UNUSED);
	}

	int EncodedFromUTF8(const char* utf8, char* encoded) const {
		int res = Call(SCI_ENCODEDFROMUTF8, utf8, encoded);
		return res;
	}

	int FindColumn(int line, int column) const {
		int res = Call(SCI_FINDCOLUMN, line, column);
		return res;
	}

	int GetCaretSticky() const {
		int res = Call(SCI_GETCARETSTICKY, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetCaretSticky(int useCaretStickyBehaviour) const {
		Call(SCI_SETCARETSTICKY, useCaretStickyBehaviour, SCI_UNUSED);
	}

	void ToggleCaretSticky() const {
		Call(SCI_TOGGLECARETSTICKY, SCI_UNUSED, SCI_UNUSED);
	}

	void SetPasteConvertEndings(bool convert) const {
		Call(SCI_SETPASTECONVERTENDINGS, convert, SCI_UNUSED);
	}

	bool GetPasteConvertEndings() const {
		int res = Call(SCI_GETPASTECONVERTENDINGS, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	void SelectionDuplicate() const {
		Call(SCI_SELECTIONDUPLICATE, SCI_UNUSED, SCI_UNUSED);
	}

	void SetCaretLineBackAlpha(int alpha) const {
		Call(SCI_SETCARETLINEBACKALPHA, alpha, SCI_UNUSED);
	}

	int GetCaretLineBackAlpha() const {
		int res = Call(SCI_GETCARETLINEBACKALPHA, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetCaretStyle(int caretStyle) const {
		Call(SCI_SETCARETSTYLE, caretStyle, SCI_UNUSED);
	}

	int GetCaretStyle() const {
		int res = Call(SCI_GETCARETSTYLE, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetIndicatorCurrent(int indicator) const {
		Call(SCI_SETINDICATORCURRENT, indicator, SCI_UNUSED);
	}

	int GetIndicatorCurrent() const {
		int res = Call(SCI_GETINDICATORCURRENT, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetIndicatorValue(int value) const {
		Call(SCI_SETINDICATORVALUE, value, SCI_UNUSED);
	}

	int GetIndicatorValue() const {
		int res = Call(SCI_GETINDICATORVALUE, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void IndicatorFillRange(int position, int fillLength) const {
		Call(SCI_INDICATORFILLRANGE, position, fillLength);
	}

	void IndicatorClearRange(int position, int clearLength) const {
		Call(SCI_INDICATORCLEARRANGE, position, clearLength);
	}

	int IndicatorAllOnFor(int position) const {
		int res = Call(SCI_INDICATORALLONFOR, position, SCI_UNUSED);
		return res;
	}

	int IndicatorValueAt(int indicator, int position) const {
		int res = Call(SCI_INDICATORVALUEAT, indicator, position);
		return res;
	}

	int IndicatorStart(int indicator, int position) const {
		int res = Call(SCI_INDICATORSTART, indicator, position);
		return res;
	}

	int IndicatorEnd(int indicator, int position) const {
		int res = Call(SCI_INDICATOREND, indicator, position);
		return res;
	}

	void SetPositionCache(int size) const {
		Call(SCI_SETPOSITIONCACHE, size, SCI_UNUSED);
	}

	int GetPositionCache() const {
		int res = Call(SCI_GETPOSITIONCACHE, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void CopyAllowLine() const {
		Call(SCI_COPYALLOWLINE, SCI_UNUSED, SCI_UNUSED);
	}

	int GetCharacterPointer() const {
		int res = Call(SCI_GETCHARACTERPOINTER, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	int GetRangePointer(int position, int rangeLength) const {
		int res = Call(SCI_GETRANGEPOINTER, position, rangeLength);
		return res;
	}

	int GetGapPosition() const {
		int res = Call(SCI_GETGAPPOSITION, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void IndicSetAlpha(int indicator, int alpha) const {
		Call(SCI_INDICSETALPHA, indicator, alpha);
	}

	int IndicGetAlpha(int indicator) const {
		int res = Call(SCI_INDICGETALPHA, indicator, SCI_UNUSED);
		return res;
	}

	void IndicSetOutlineAlpha(int indicator, int alpha) const {
		Call(SCI_INDICSETOUTLINEALPHA, indicator, alpha);
	}

	int IndicGetOutlineAlpha(int indicator) const {
		int res = Call(SCI_INDICGETOUTLINEALPHA, indicator, SCI_UNUSED);
		return res;
	}

	void SetExtraAscent(int extraAscent) const {
		Call(SCI_SETEXTRAASCENT, extraAscent, SCI_UNUSED);
	}

	int GetExtraAscent() const {
		int res = Call(SCI_GETEXTRAASCENT, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetExtraDescent(int extraDescent) const {
		Call(SCI_SETEXTRADESCENT, extraDescent, SCI_UNUSED);
	}

	int GetExtraDescent() const {
		int res = Call(SCI_GETEXTRADESCENT, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	int MarkerSymbolDefined(int markerNumber) const {
		int res = Call(SCI_MARKERSYMBOLDEFINED, markerNumber, SCI_UNUSED);
		return res;
	}

	void MarginSetText(int line, const char* text) const {
		Call(SCI_MARGINSETTEXT, line, text);
	}

	int MarginGetText(int line, char* text) const {
		int res = Call(SCI_MARGINGETTEXT, line, text);
		return res;
	}

	void MarginSetStyle(int line, int style) const {
		Call(SCI_MARGINSETSTYLE, line, style);
	}

	int MarginGetStyle(int line) const {
		int res = Call(SCI_MARGINGETSTYLE, line, SCI_UNUSED);
		return res;
	}

	void MarginSetStyles(int line, const char* styles) const {
		Call(SCI_MARGINSETSTYLES, line, styles);
	}

	int MarginGetStyles(int line, char* styles) const {
		int res = Call(SCI_MARGINGETSTYLES, line, styles);
		return res;
	}

	void MarginTextClearAll() const {
		Call(SCI_MARGINTEXTCLEARALL, SCI_UNUSED, SCI_UNUSED);
	}

	void MarginSetStyleOffset(int style) const {
		Call(SCI_MARGINSETSTYLEOFFSET, style, SCI_UNUSED);
	}

	int MarginGetStyleOffset() const {
		int res = Call(SCI_MARGINGETSTYLEOFFSET, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetMarginOptions(int marginOptions) const {
		Call(SCI_SETMARGINOPTIONS, marginOptions, SCI_UNUSED);
	}

	int GetMarginOptions() const {
		int res = Call(SCI_GETMARGINOPTIONS, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void AnnotationSetText(int line, const char* text) const {
		Call(SCI_ANNOTATIONSETTEXT, line, text);
	}

	int AnnotationGetText(int line, char* text) const {
		int res = Call(SCI_ANNOTATIONGETTEXT, line, text);
		return res;
	}

	void AnnotationSetStyle(int line, int style) const {
		Call(SCI_ANNOTATIONSETSTYLE, line, style);
	}

	int AnnotationGetStyle(int line) const {
		int res = Call(SCI_ANNOTATIONGETSTYLE, line, SCI_UNUSED);
		return res;
	}

	void AnnotationSetStyles(int line, const char* styles) const {
		Call(SCI_ANNOTATIONSETSTYLES, line, styles);
	}

	int AnnotationGetStyles(int line, char* styles) const {
		int res = Call(SCI_ANNOTATIONGETSTYLES, line, styles);
		return res;
	}

	int AnnotationGetLines(int line) const {
		int res = Call(SCI_ANNOTATIONGETLINES, line, SCI_UNUSED);
		return res;
	}

	void AnnotationClearAll() const {
		Call(SCI_ANNOTATIONCLEARALL, SCI_UNUSED, SCI_UNUSED);
	}

	void AnnotationSetVisible(int visible) const {
		Call(SCI_ANNOTATIONSETVISIBLE, visible, SCI_UNUSED);
	}

	int AnnotationGetVisible() const {
		int res = Call(SCI_ANNOTATIONGETVISIBLE, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void AnnotationSetStyleOffset(int style) const {
		Call(SCI_ANNOTATIONSETSTYLEOFFSET, style, SCI_UNUSED);
	}

	int AnnotationGetStyleOffset() const {
		int res = Call(SCI_ANNOTATIONGETSTYLEOFFSET, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void ReleaseAllExtendedStyles() const {
		Call(SCI_RELEASEALLEXTENDEDSTYLES, SCI_UNUSED, SCI_UNUSED);
	}

	int AllocateExtendedStyles(int numberStyles) const {
		int res = Call(SCI_ALLOCATEEXTENDEDSTYLES, numberStyles, SCI_UNUSED);
		return res;
	}

	void AddUndoAction(int token, int flags) const {
		Call(SCI_ADDUNDOACTION, token, flags);
	}

	int CharPositionFromPoint(int x, int y) const {
		int res = Call(SCI_CHARPOSITIONFROMPOINT, x, y);
		return res;
	}

	int CharPositionFromPointClose(int x, int y) const {
		int res = Call(SCI_CHARPOSITIONFROMPOINTCLOSE, x, y);
		return res;
	}

	void SetMouseSelectionRectangularSwitch(bool mouseSelectionRectangularSwitch) const {
		Call(SCI_SETMOUSESELECTIONRECTANGULARSWITCH, mouseSelectionRectangularSwitch, SCI_UNUSED);
	}

	bool GetMouseSelectionRectangularSwitch() const {
		int res = Call(SCI_GETMOUSESELECTIONRECTANGULARSWITCH, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	void SetMultipleSelection(bool multipleSelection) const {
		Call(SCI_SETMULTIPLESELECTION, multipleSelection, SCI_UNUSED);
	}

	bool GetMultipleSelection() const {
		int res = Call(SCI_GETMULTIPLESELECTION, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	void SetAdditionalSelectionTyping(bool additionalSelectionTyping) const {
		Call(SCI_SETADDITIONALSELECTIONTYPING, additionalSelectionTyping, SCI_UNUSED);
	}

	bool GetAdditionalSelectionTyping() const {
		int res = Call(SCI_GETADDITIONALSELECTIONTYPING, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	void SetAdditionalCaretsBlink(bool additionalCaretsBlink) const {
		Call(SCI_SETADDITIONALCARETSBLINK, additionalCaretsBlink, SCI_UNUSED);
	}

	bool GetAdditionalCaretsBlink() const {
		int res = Call(SCI_GETADDITIONALCARETSBLINK, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	void SetAdditionalCaretsVisible(bool additionalCaretsBlink) const {
		Call(SCI_SETADDITIONALCARETSVISIBLE, additionalCaretsBlink, SCI_UNUSED);
	}

	bool GetAdditionalCaretsVisible() const {
		int res = Call(SCI_GETADDITIONALCARETSVISIBLE, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	int GetSelections() const {
		int res = Call(SCI_GETSELECTIONS, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	bool GetSelectionEmpty() const {
		int res = Call(SCI_GETSELECTIONEMPTY, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	void ClearSelections() const {
		Call(SCI_CLEARSELECTIONS, SCI_UNUSED, SCI_UNUSED);
	}

	int SetSelection(int caret, int anchor) const {
		int res = Call(SCI_SETSELECTION, caret, anchor);
		return res;
	}

	int AddSelection(int caret, int anchor) const {
		int res = Call(SCI_ADDSELECTION, caret, anchor);
		return res;
	}

	void DropSelectionN(int selection) const {
		Call(SCI_DROPSELECTIONN, selection, SCI_UNUSED);
	}

	void SetMainSelection(int selection) const {
		Call(SCI_SETMAINSELECTION, selection, SCI_UNUSED);
	}

	int GetMainSelection() const {
		int res = Call(SCI_GETMAINSELECTION, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetSelectionNCaret(int selection, int pos) const {
		Call(SCI_SETSELECTIONNCARET, selection, pos);
	}

	int GetSelectionNCaret(int selection) const {
		int res = Call(SCI_GETSELECTIONNCARET, selection, SCI_UNUSED);
		return res;
	}

	void SetSelectionNAnchor(int selection, int posAnchor) const {
		Call(SCI_SETSELECTIONNANCHOR, selection, posAnchor);
	}

	int GetSelectionNAnchor(int selection) const {
		int res = Call(SCI_GETSELECTIONNANCHOR, selection, SCI_UNUSED);
		return res;
	}

	void SetSelectionNCaretVirtualSpace(int selection, int space) const {
		Call(SCI_SETSELECTIONNCARETVIRTUALSPACE, selection, space);
	}

	int GetSelectionNCaretVirtualSpace(int selection) const {
		int res = Call(SCI_GETSELECTIONNCARETVIRTUALSPACE, selection, SCI_UNUSED);
		return res;
	}

	void SetSelectionNAnchorVirtualSpace(int selection, int space) const {
		Call(SCI_SETSELECTIONNANCHORVIRTUALSPACE, selection, space);
	}

	int GetSelectionNAnchorVirtualSpace(int selection) const {
		int res = Call(SCI_GETSELECTIONNANCHORVIRTUALSPACE, selection, SCI_UNUSED);
		return res;
	}

	void SetSelectionNStart(int selection, int pos) const {
		Call(SCI_SETSELECTIONNSTART, selection, pos);
	}

	int GetSelectionNStart(int selection) const {
		int res = Call(SCI_GETSELECTIONNSTART, selection, SCI_UNUSED);
		return res;
	}

	void SetSelectionNEnd(int selection, int pos) const {
		Call(SCI_SETSELECTIONNEND, selection, pos);
	}

	int GetSelectionNEnd(int selection) const {
		int res = Call(SCI_GETSELECTIONNEND, selection, SCI_UNUSED);
		return res;
	}

	void SetRectangularSelectionCaret(int pos) const {
		Call(SCI_SETRECTANGULARSELECTIONCARET, pos, SCI_UNUSED);
	}

	int GetRectangularSelectionCaret() const {
		int res = Call(SCI_GETRECTANGULARSELECTIONCARET, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetRectangularSelectionAnchor(int posAnchor) const {
		Call(SCI_SETRECTANGULARSELECTIONANCHOR, posAnchor, SCI_UNUSED);
	}

	int GetRectangularSelectionAnchor() const {
		int res = Call(SCI_GETRECTANGULARSELECTIONANCHOR, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetRectangularSelectionCaretVirtualSpace(int space) const {
		Call(SCI_SETRECTANGULARSELECTIONCARETVIRTUALSPACE, space, SCI_UNUSED);
	}

	int GetRectangularSelectionCaretVirtualSpace() const {
		int res = Call(SCI_GETRECTANGULARSELECTIONCARETVIRTUALSPACE, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetRectangularSelectionAnchorVirtualSpace(int space) const {
		Call(SCI_SETRECTANGULARSELECTIONANCHORVIRTUALSPACE, space, SCI_UNUSED);
	}

	int GetRectangularSelectionAnchorVirtualSpace() const {
		int res = Call(SCI_GETRECTANGULARSELECTIONANCHORVIRTUALSPACE, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetVirtualSpaceOptions(int virtualSpaceOptions) const {
		Call(SCI_SETVIRTUALSPACEOPTIONS, virtualSpaceOptions, SCI_UNUSED);
	}

	int GetVirtualSpaceOptions() const {
		int res = Call(SCI_GETVIRTUALSPACEOPTIONS, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetRectangularSelectionModifier(int modifier) const {
		Call(SCI_SETRECTANGULARSELECTIONMODIFIER, modifier, SCI_UNUSED);
	}

	int GetRectangularSelectionModifier() const {
		int res = Call(SCI_GETRECTANGULARSELECTIONMODIFIER, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetAdditionalSelFore(int fore) const {
		Call(SCI_SETADDITIONALSELFORE, fore, SCI_UNUSED);
	}

	void SetAdditionalSelBack(int back) const {
		Call(SCI_SETADDITIONALSELBACK, back, SCI_UNUSED);
	}

	void SetAdditionalSelAlpha(int alpha) const {
		Call(SCI_SETADDITIONALSELALPHA, alpha, SCI_UNUSED);
	}

	int GetAdditionalSelAlpha() const {
		int res = Call(SCI_GETADDITIONALSELALPHA, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetAdditionalCaretFore(int fore) const {
		Call(SCI_SETADDITIONALCARETFORE, fore, SCI_UNUSED);
	}

	int GetAdditionalCaretFore() const {
		int res = Call(SCI_GETADDITIONALCARETFORE, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void RotateSelection() const {
		Call(SCI_ROTATESELECTION, SCI_UNUSED, SCI_UNUSED);
	}

	void SwapMainAnchorCaret() const {
		Call(SCI_SWAPMAINANCHORCARET, SCI_UNUSED, SCI_UNUSED);
	}

	int ChangeLexerState(int start, int end) const {
		int res = Call(SCI_CHANGELEXERSTATE, start, end);
		return res;
	}

	int ContractedFoldNext(int lineStart) const {
		int res = Call(SCI_CONTRACTEDFOLDNEXT, lineStart, SCI_UNUSED);
		return res;
	}

	void VerticalCentreCaret() const {
		Call(SCI_VERTICALCENTRECARET, SCI_UNUSED, SCI_UNUSED);
	}

	void MoveSelectedLinesUp() const {
		Call(SCI_MOVESELECTEDLINESUP, SCI_UNUSED, SCI_UNUSED);
	}

	void MoveSelectedLinesDown() const {
		Call(SCI_MOVESELECTEDLINESDOWN, SCI_UNUSED, SCI_UNUSED);
	}

	void SetIdentifier(int identifier) const {
		Call(SCI_SETIDENTIFIER, identifier, SCI_UNUSED);
	}

	int GetIdentifier() const {
		int res = Call(SCI_GETIDENTIFIER, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void RGBAImageSetWidth(int width) const {
		Call(SCI_RGBAIMAGESETWIDTH, width, SCI_UNUSED);
	}

	void RGBAImageSetHeight(int height) const {
		Call(SCI_RGBAIMAGESETHEIGHT, height, SCI_UNUSED);
	}

	void RGBAImageSetScale(int scalePercent) const {
		Call(SCI_RGBAIMAGESETSCALE, scalePercent, SCI_UNUSED);
	}

	void MarkerDefineRGBAImage(int markerNumber, const char* pixels) const {
		Call(SCI_MARKERDEFINERGBAIMAGE, markerNumber, pixels);
	}

	void RegisterRGBAImage(int type, const char* pixels) const {
		Call(SCI_REGISTERRGBAIMAGE, type, pixels);
	}

	void ScrollToStart() const {
		Call(SCI_SCROLLTOSTART, SCI_UNUSED, SCI_UNUSED);
	}

	void ScrollToEnd() const {
		Call(SCI_SCROLLTOEND, SCI_UNUSED, SCI_UNUSED);
	}

	void SetTechnology(int technology) const {
		Call(SCI_SETTECHNOLOGY, technology, SCI_UNUSED);
	}

	int GetTechnology() const {
		int res = Call(SCI_GETTECHNOLOGY, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	int CreateLoader(int bytes) const {
		int res = Call(SCI_CREATELOADER, bytes, SCI_UNUSED);
		return res;
	}

	void FindIndicatorShow(int start, int end) const {
		Call(SCI_FINDINDICATORSHOW, start, end);
	}

	void FindIndicatorFlash(int start, int end) const {
		Call(SCI_FINDINDICATORFLASH, start, end);
	}

	void FindIndicatorHide() const {
		Call(SCI_FINDINDICATORHIDE, SCI_UNUSED, SCI_UNUSED);
	}

	void VCHomeDisplay() const {
		Call(SCI_VCHOMEDISPLAY, SCI_UNUSED, SCI_UNUSED);
	}

	void VCHomeDisplayExtend() const {
		Call(SCI_VCHOMEDISPLAYEXTEND, SCI_UNUSED, SCI_UNUSED);
	}

	bool GetCaretLineVisibleAlways() const {
		int res = Call(SCI_GETCARETLINEVISIBLEALWAYS, SCI_UNUSED, SCI_UNUSED);
		return res != 0;
	}

	void SetCaretLineVisibleAlways(bool alwaysVisible) const {
		Call(SCI_SETCARETLINEVISIBLEALWAYS, alwaysVisible, SCI_UNUSED);
	}

	void SetLineEndTypesAllowed(int lineEndBitSet) const {
		Call(SCI_SETLINEENDTYPESALLOWED, lineEndBitSet, SCI_UNUSED);
	}

	int GetLineEndTypesAllowed() const {
		int res = Call(SCI_GETLINEENDTYPESALLOWED, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	int GetLineEndTypesActive() const {
		int res = Call(SCI_GETLINEENDTYPESACTIVE, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void SetRepresentation(const char* encodedCharacter, const char* representation) const {
		Call(SCI_SETREPRESENTATION, encodedCharacter, representation);
	}

	int GetRepresentation(const char* encodedCharacter, char* representation) const {
		int res = Call(SCI_GETREPRESENTATION, encodedCharacter, representation);
		return res;
	}

	void ClearRepresentation(const char* encodedCharacter) const {
		Call(SCI_CLEARREPRESENTATION, encodedCharacter, SCI_UNUSED);
	}

	void StartRecord() const {
		Call(SCI_STARTRECORD, SCI_UNUSED, SCI_UNUSED);
	}

	void StopRecord() const {
		Call(SCI_STOPRECORD, SCI_UNUSED, SCI_UNUSED);
	}

	void SetLexer(int lexer) const {
		Call(SCI_SETLEXER, lexer, SCI_UNUSED);
	}

	int GetLexer() const {
		int res = Call(SCI_GETLEXER, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	void Colourise(int start, int end) const {
		Call(SCI_COLOURISE, start, end);
	}

	void SetProperty(const char* key, const char* value) const {
		Call(SCI_SETPROPERTY, key, value);
	}

	void SetKeyWords(int keywordSet, const char* keyWords) const {
		Call(SCI_SETKEYWORDS, keywordSet, keyWords);
	}

	void SetLexerLanguage(const char* language) const {
		Call(SCI_SETLEXERLANGUAGE, SCI_UNUSED, language);
	}

	void LoadLexerLibrary(const char* path) const {
		Call(SCI_LOADLEXERLIBRARY, SCI_UNUSED, path);
	}

	int GetProperty(const char* key, char* buf) const {
		int res = Call(SCI_GETPROPERTY, key, buf);
		return res;
	}

	int GetPropertyExpanded(const char* key, char* buf) const {
		int res = Call(SCI_GETPROPERTYEXPANDED, key, buf);
		return res;
	}

	int GetPropertyInt(const char* key) const {
		int res = Call(SCI_GETPROPERTYINT, key, SCI_UNUSED);
		return res;
	}

	int GetStyleBitsNeeded() const {
		int res = Call(SCI_GETSTYLEBITSNEEDED, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	int GetLexerLanguage(char* text) const {
		int res = Call(SCI_GETLEXERLANGUAGE, SCI_UNUSED, text);
		return res;
	}

	int PrivateLexerCall(int operation, int pointer) const {
		int res = Call(SCI_PRIVATELEXERCALL, operation, pointer);
		return res;
	}

	int PropertyNames(char* names) const {
		int res = Call(SCI_PROPERTYNAMES, SCI_UNUSED, names);
		return res;
	}

	int PropertyType(const char* name) const {
		int res = Call(SCI_PROPERTYTYPE, name, SCI_UNUSED);
		return res;
	}

	int DescribeProperty(const char* name, char* description) const {
		int res = Call(SCI_DESCRIBEPROPERTY, name, description);
		return res;
	}

	int DescribeKeyWordSets(char* descriptions) const {
		int res = Call(SCI_DESCRIBEKEYWORDSETS, SCI_UNUSED, descriptions);
		return res;
	}

	int GetLineEndTypesSupported() const {
		int res = Call(SCI_GETLINEENDTYPESSUPPORTED, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	int AllocateSubStyles(int styleBase, int numberStyles) const {
		int res = Call(SCI_ALLOCATESUBSTYLES, styleBase, numberStyles);
		return res;
	}

	int GetSubStylesStart(int styleBase) const {
		int res = Call(SCI_GETSUBSTYLESSTART, styleBase, SCI_UNUSED);
		return res;
	}

	int GetSubStylesLength(int styleBase) const {
		int res = Call(SCI_GETSUBSTYLESLENGTH, styleBase, SCI_UNUSED);
		return res;
	}

	int GetStyleFromSubStyle(int subStyle) const {
		int res = Call(SCI_GETSTYLEFROMSUBSTYLE, subStyle, SCI_UNUSED);
		return res;
	}

	int GetPrimaryStyleFromStyle(int style) const {
		int res = Call(SCI_GETPRIMARYSTYLEFROMSTYLE, style, SCI_UNUSED);
		return res;
	}

	void FreeSubStyles() const {
		Call(SCI_FREESUBSTYLES, SCI_UNUSED, SCI_UNUSED);
	}

	void SetIdentifiers(int style, const char* identifiers) const {
		Call(SCI_SETIDENTIFIERS, style, identifiers);
	}

	int DistanceToSecondaryStyles() const {
		int res = Call(SCI_DISTANCETOSECONDARYSTYLES, SCI_UNUSED, SCI_UNUSED);
		return res;
	}

	int GetSubStyleBases(char* styles) const {
		int res = Call(SCI_GETSUBSTYLEBASES, SCI_UNUSED, styles);
		return res;
	}

	/* --Autogenerated -- end of section automatically generated from Scintilla.iface */
};
